
GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/5eaf371e12e6bf26c0b68afe

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
   "name": "Amazing Person",
   "subscribedToChannel": "Web Dev Simplified"
}

###

PATCH  http://localhost:3000/subscribers/5eaf371e12e6bf26c0b68afe
Content-Type: application/json

{
   "name": "Logan",
   "subscribedToChannel": "Logan Paul"
}

###

DELETE http://localhost:3000/subscribers/5eaf357d12e6bf26c0b68afb

###


